### ISSUE TITLE
bug: pas d’action sous les toot

### ISSUE THREAD

**Issue by Atn-D** [BDX-town/elk#19]
Connecté avec un compte Iceshrim.net qui marche bien avec Elk.zone
Je n’ai plus d’actions sous les posts

![image](https://github.com/user-attachments/assets/2d5d6326-173c-47fb-93b3-0e6e2022258b)

(je précise qu’Iceshrimp.NET se veux 100% compatible avec les FE Akkoma, features custom comme les react‑emoji comprit)

**Comment by Cl0v1s** [comment]
Not a bug, you activated the zen mode

**Comment by Atn-D** [comment]
Le mode zen est désactivé.
Mais si je l’active, puis le coupe, ça fix le problème !
Mais d’est que je change d’onglet, le pb est de retour, et je dois à nouveau activer puis désactiver le mode zen…

**Comment by Cl0v1s** [comment]
Je suis preneur de toutes les informations que tu peux transmettre ! 

(Instance, version des logiciels, options activées/désactivées, erreurs dans la console etc..)

**Comment by Atn-D** [comment]
Instance : https://iceshrimp1.antoined.fr/ (Tu peux t’inscrire pour avoir un compte de test si tu veux)
Logiciel : Librewolf avec mes options, mais aussi Zen browser avec tout par defaut.
Serveur : https://iceshrimp.net (docker le plus à jour)
Options : Tout par defaut
Erreur console : 
```
Accès au stockage automatiquement accordé pour le partitionnement d’état dynamique « https://iceshrimp1.antoined.fr/ » sur « https://mangane.bdx.town/ ». [callback](https://mangane.bdx.town/signin/callback?server=iceshrimp1.antoined.fr&token=2gwU9hLRAddQnVKEFMnSRNQtJhv7zs0t&vapid_key=BEERsKSeYC6SqXgr6Y-J2oNRG7cwnlnmSpv6JBfc2qdgeDysFxKs03QIz1p4QNgMPJi0NiXfHBKdd0bRRT9_ZI4)
Cannot fetch preferences: l_: NotImplemented
````
Puis j’ai en boucle l’erreure que j’ai annoncé sur ce ticket, mais sans même avoir cliqué sur les like/emoji
https://github.com/BDX-town/elk/issues/21

Je pense que ça vient de la !

**Comment by Cl0v1s** [comment]
Ah oui ça vient effectivement de là bien vu, voir la réponse apporté dans le ticket #21 du coup !
