### ISSUE TITLE
bug: ReactEmoji

### ISSUE THREAD

**Issue by Atn-D** [BDX-town/elk#21]
Quand je like avec un react emoji, rien ne se passe, et j’ai cette erreur dans la console : 
```
TypeError: t.value.emojiReactions is undefined
    NuxtJS 111
        toggleReact
        t
        Jb
        ri
        Dn
        Dn
        n
        Gn
        Kb
        Qb
        S
        b
        p
        E
        run
        X
        ne
        H
        p
        R
        O
        p
        R
        S
        b
        p
        R
        O
        p
        R
        O
        p
        R
        S
        b
        p
        R
        O
        p
        T
        w
        b
        p
        E
        run
        ue
        H
        p
        dt
        Q
        O
        p
        T
        w
        b
        p
        E
        run
        runIfDirty
        ri
        Zm
        promise callback*Qm
        Ju
        scheduler
        trigger
        Vu
        Kn
        set
        set
        $_ensureTeleport
        $_applyShow
        setTimeout handler*$_scheduleShow
        show
        $_autoShowHide
        ri
        Dn
        call
        m
        id
        re
        E
        run
        ue
        H
        p
        E
        run
        ue
        H
        p
        T
        w
        b
        p
        E
        run
        runIfDirty
        ri
        Zm
        promise callback*Qm
        Ju
        scheduler
        trigger
        Vu
        notify
        trigger
        set value
        i
        ri
        Dn
        n
DwjFp-Y4.js:14:662

```

C’est peu être un bug a déclarer coté Iceshrimp ?

**Comment by Cl0v1s** [comment]
Visiblement les reactions iceshrimp ne sont pas placées dans le champ emojiReaction d'un status 

Je dirais pas que c'est un bug iceshrimp, mais simplement une diff entre akkoma et iceshrimp

**Comment by Cl0v1s** [comment]
Si le format est le même, tu peux juste me communiquer le format / nom du champ, je peux essayer de le gérer en plus, même si l'idée c'est de faire un front akkoma !

**Comment by Atn-D** [comment]
Visiblement ça devrait déjà être bon…

![image](https://github.com/user-attachments/assets/f089303b-fcda-4524-86dc-4d77aa5ac556)

**Comment by Cl0v1s** [comment]
T'as un lien vers leur api ? 
Le chamo utilisé par pleroma n'est pas pleroma.emoji_reactions mais pleroma:emoji_reactions (c'est pas un sous-objet mais bien un champ dont la clef contient ":")

**Comment by Cl0v1s** [comment]
Je vais rejeter un œil dans le code avec ton erreur en tête !

**Comment by Atn-D** [comment]
Voilà le swagger API :
https://iceshrimp1.antoined.fr/swagger/index.html

Et la doc Iceshrimp : 
https://kb.iceshrimp.dev/s/docs/doc/interacting-with-the-api-QCjhV8TaYA

**Comment by Cl0v1s** [comment]
Du coup, je constate effectivement des différences entre akkoma et iceshrimp: 

Le endpoint `/api/iceshrimp/notes/{id}` qui semble retourner un status ne présente pas de champ `emoji_reactions`, ni `pleroma.emoji_reactions` ni `akkoma.emoji_reactions` comme le fait l'API d'akkoma / pleroma 

On a bien un champ `reactions` mais le format n'est pas identique à celui de `emoji_reactions` d'Akkoma 

Le format d'akkoma est le suivant: 

https://docs.akkoma.dev/stable/development/API/pleroma_api/#get-apiv1pleromastatusesidreactions
```
  {"name": "😀", "count": 2, "me": true, "accountIds": ['abc', 'def']},
```

**Comment by Atn-D** [comment]
J’ai eu une réponse : 
> « ah, that's the iceshrimp API. that one's not supposed to be compatible with mastodon clients at all but entirely custom.
the regular mastodon api should work as intended though, unsure why they're trying to use the iceshrimp api »

**Comment by Cl0v1s** [comment]
Ah alors j'utilise pas l'api iceshrimp ! J'ai simplement regardé les ressources que tu m'as transmises, d'où la confusion 

Est ce qu'il existe une documentation de leur implémentation de l'api mastodon ? 

Très visiblement cependant le champ `emoji_reactions` à la racine de l'objet `Status` n'existe pas sous iceshrimp contrairement à ce qui existe sous Akkoma depuis la 3.2 
Si ils veulent être compliant je pense qu'il faut ajouter ça.

De mon côté je vais proposer un fix pour essayer de target `pleroma.emoji_reactions` mais en l'absence de specs claires je suis un peu a l'aveugle

**Comment by Cl0v1s** [comment]
Ce sera fixé quand ce fix sera déployé https://github.com/BDX-town/elk/commit/df71255c35ec782a07ddd592ef069fb4b8d4b10a si mes hypothèses sont correctes

**Comment by Atn-D** [comment]
C’est fixé ! Bravo :clap: 

C’était quoi tes hypothèses ?

**Comment by Cl0v1s** [comment]
Celles dans le post au dessus ! En revanche, iceshrimp n'est donc pas réellement compatible avec l'API d'akkoma de fait ! :)
