### ISSUE TITLE
feat: quote post

### ISSUE THREAD

**Issue by Atn-D** [BDX-town/elk#27]
Implémenter le fait de pouvoir citer un post dans un autre.

**Comment by Cl0v1s** [comment]
La MR est ok si tu veux / peux la relire !

**Comment by Atn-D** [comment]
Je ne suis pas assez a l’aise en js/vue pour juger du code, mais c’était intéressant de voir les modifications de ton commit.
Je ferais un MR pour fixer le style si je trouve cela nécessaire après deploy :)

**Comment by Cl0v1s** [comment]
C'est mergé, la CI nous fait un build et je deploy
